namespace MyUtilities.Constants.Enum
{
    public enum BudgetCategories
    {
        uninitialized = 0,
        cable = 1,
        carInsurance = 2,
        carPayment = 3,
        clothing = 4,
        creditCard = 5,
        dental = 6,
        eatingOut = 7,
        electricity = 8,
        emergencyFund = 9,
        entertainment = 10,
        gas = 11,
        gasoline = 12,
        gifts = 13,
        groceries = 14,
        gym = 15,
        healthInsurance = 16,
        homeInsurance = 17,
        homeownerDues = 18,
        internet = 19,
        investment = 20,
        lifeInsurance = 21,
        medical = 22,
        mortgage = 23,
        other = 24,
        personalLoan = 25,
        phone = 26,
        rent = 27,
        retirement = 28,
        salary = 29,
        savings = 30,
        streaming = 31,
        studentLoan = 32,
        subscriptions = 33,
        trash = 34,
        travel = 34,
        vacation = 35,
        vision = 37,
        water = 38,
        others = 39,
        outOfRange,
    }
}