namespace Database.Trupanion.Entity.TruDat.Dbo;

public class TruDatDboAssessmentTemplate2
{
    public int AssessmentDataId { get; set; }
    public int VersionId { get; set; }
    public int? VersionNumber { get; set; }
    public string? Postaladdress { get; set; }
    public string? Clinicname { get; set; }
    public string? Clinicaddress { get; set; }
    public string? Cliniccity { get; set; }
    public string? Clinicstate { get; set; }
    public string? Cliniczipcode { get; set; }
    public string? PilotContactName { get; set; }
    public string? PilotContactEmail { get; set; }
    public string? PilotFax { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zipcode { get; set; }
    public string? Currentdate { get; set; }
    public string? Currentdate2 { get; set; }
    public string? Firstname { get; set; }
    public string? Lastname { get; set; }
    public string? Petname { get; set; }
    public string? Invoicenumbers { get; set; }
    public string? Dateofloss { get; set; }
    public string? Enrolldate { get; set; }
    public string? Policynumber { get; set; }
    public string? Policy { get; set; }
    public int Claimid { get; set; }
    public string? Adjuster { get; set; }
    public string? Adjusteremailid { get; set; }
    public string? Underwriter { get; set; }
    public string? Totalclaimed { get; set; }
    public string? Totalclaimpaid { get; set; }
    public string? PetOwnerPortion { get; set; }
    public string? Lettercomments { get; set; }
    public string? Comments { get; set; }
    public int? Topchecknumber { get; set; }
    public string? Condition { get; set; }
    public string? Amountinwords { get; set; }
    public string? Totalclaimspaid { get; set; }
    public string? Checkdate { get; set; }
    public string? Fullname { get; set; }
    public string? Province { get; set; }
    public string? Postalcode { get; set; }
    public int? Downchecknumber { get; set; }
    public string? Accountnumber { get; set; }
    public string? Closeddate { get; set; }
    public int Claimnumber { get; set; }
    public string? Inceptiondate { get; set; }
    public string? Invoicesubtotal { get; set; }
    public int Ownerid { get; set; }
    public string? Emailaddress { get; set; }
    public string? HtmlString { get; set; }
    public string? Bankname { get; set; }
    public string? Bankaddress { get; set; }
    public string? Bankzipcode { get; set; }
    public string? Bankcity { get; set; }
    public string? Bankstate { get; set; }
    public string? Statemssg { get; set; }
    public string? Claimfax { get; set; }
    public string? Claimphone { get; set; }
    public string? Claimurgentfax { get; set; }
    public string? Claimemail { get; set; }
    public string? Gender { get; set; }
}
