namespace Database.Trupanion.Entity.TruDat.Dbo;

public class TruDatDboDedHistoryImport
{
    public string? PolicyNumber { get; set; }
    public string? PetName { get; set; }
    public double? CostAmount { get; set; }
    public DateTime? EffectiveFrom { get; set; }
    public DateTime? EffectiveTo { get; set; }
    public string? NoDeductibleChange { get; set; }
    public string? F7 { get; set; }
    public string? F8 { get; set; }
    public string? F9 { get; set; }
    public string? F10 { get; set; }
    public string? F11 { get; set; }
    public string? F12 { get; set; }
    public string? F13 { get; set; }
    public string? F14 { get; set; }
    public string? F15 { get; set; }
    public string? F16 { get; set; }
    public string? F17 { get; set; }
    public string? F18 { get; set; }
    public string? F19 { get; set; }
    public string? F20 { get; set; }
    public string? F21 { get; set; }
    public string? F22 { get; set; }
    public string? F23 { get; set; }
    public string? F24 { get; set; }
    public string? F25 { get; set; }
    public string? F26 { get; set; }
    public string? F27 { get; set; }
    public string? F28 { get; set; }
    public string? F29 { get; set; }
    public DateTime? F30 { get; set; }
    public DateTime? F31 { get; set; }
    public string? F32 { get; set; }
    public string? F33 { get; set; }
    public string? F34 { get; set; }
    public string? F35 { get; set; }
    public string? F36 { get; set; }
    public string? F37 { get; set; }
    public string? F38 { get; set; }
    public string? F39 { get; set; }
    public string? F40 { get; set; }
    public string? F41 { get; set; }
    public string? F42 { get; set; }
    public string? F43 { get; set; }
    public string? F44 { get; set; }
    public string? F45 { get; set; }
    public string? F46 { get; set; }
    public string? F47 { get; set; }
    public string? F48 { get; set; }
    public string? F49 { get; set; }
    public string? F50 { get; set; }
    public string? F51 { get; set; }
    public string? F52 { get; set; }
    public string? F53 { get; set; }
    public string? F54 { get; set; }
    public string? F55 { get; set; }
    public string? F56 { get; set; }
    public string? F57 { get; set; }
    public string? F58 { get; set; }
    public string? F59 { get; set; }
    public string? F60 { get; set; }
    public string? F61 { get; set; }
    public string? F62 { get; set; }
    public string? F63 { get; set; }
    public string? F64 { get; set; }
    public string? F65 { get; set; }
    public string? F66 { get; set; }
    public string? F67 { get; set; }
    public string? F68 { get; set; }
    public string? F69 { get; set; }
    public string? F70 { get; set; }
    public string? F71 { get; set; }
    public string? F72 { get; set; }
    public string? F73 { get; set; }
    public string? F74 { get; set; }
    public string? F75 { get; set; }
    public string? F76 { get; set; }
    public string? F77 { get; set; }
    public string? F78 { get; set; }
    public string? F79 { get; set; }
    public string? F80 { get; set; }
    public string? F81 { get; set; }
    public string? F82 { get; set; }
    public string? F83 { get; set; }
    public string? F84 { get; set; }
    public string? F85 { get; set; }
    public string? F86 { get; set; }
    public string? F87 { get; set; }
    public string? F88 { get; set; }
    public string? F89 { get; set; }
    public string? F90 { get; set; }
    public string? F91 { get; set; }
    public string? F92 { get; set; }
    public string? F93 { get; set; }
    public string? F94 { get; set; }
    public string? F95 { get; set; }
    public string? F96 { get; set; }
    public string? F97 { get; set; }
    public string? F98 { get; set; }
    public string? F99 { get; set; }
    public string? F100 { get; set; }
    public string? F101 { get; set; }
    public string? F102 { get; set; }
    public string? F103 { get; set; }
    public string? F104 { get; set; }
    public string? F105 { get; set; }
    public string? F106 { get; set; }
}
