namespace Database.Trupanion.Entity.TruDat.Dbo;

public class TruDatDboZipCodesDatabaseDeluxeBusiness
{
    public string? ZipCode { get; set; }
    public string? PrimaryRecord { get; set; }
    public string? Population { get; set; }
    public string? HouseholdsPerZipCode { get; set; }
    public string? WhitePopulation { get; set; }
    public string? BlackPopulation { get; set; }
    public string? HispanicPopulation { get; set; }
    public string? AsianPopulation { get; set; }
    public string? HawaiianPopulation { get; set; }
    public string? IndianPopulation { get; set; }
    public string? OtherPopulation { get; set; }
    public string? MalePopulation { get; set; }
    public string? FemalePopulation { get; set; }
    public string? PersonsPerHousehold { get; set; }
    public string? AverageHouseValue { get; set; }
    public string? IncomePerHousehold { get; set; }
    public string? MedianAge { get; set; }
    public string? MedianAgeMale { get; set; }
    public string? MedianAgeFemale { get; set; }
    public string? Latitude { get; set; }
    public string? Longitude { get; set; }
    public string? Elevation { get; set; }
    public string? State { get; set; }
    public string? StateFullName { get; set; }
    public string? CityType { get; set; }
    public string? CityAliasAbbreviation { get; set; }
    public string? AreaCode { get; set; }
    public string? City { get; set; }
    public string? CityAliasName { get; set; }
    public string? County { get; set; }
    public string? CountyFips { get; set; }
    public string? StateFips { get; set; }
    public string? TimeZone { get; set; }
    public string? DayLightSaving { get; set; }
    public string? Msa { get; set; }
    public string? Pmsa { get; set; }
    public string? Csa { get; set; }
    public string? Cbsa { get; set; }
    public string? CbsaDiv { get; set; }
    public string? Cbsatype { get; set; }
    public string? Cbsaname { get; set; }
    public string? Pmsaname { get; set; }
    public string? Region { get; set; }
    public string? Division { get; set; }
    public string? MailingName { get; set; }
    public string? NumberOfBusinesses { get; set; }
    public string? NumberOfEmployees { get; set; }
    public string? BusinessFirstQuarterPayroll { get; set; }
    public string? BusinessAnnualPayroll { get; set; }
    public string? BusinessEmploymentFlag { get; set; }
    public string? GrowthRank { get; set; }
    public string? GrowthHousingUnits2003 { get; set; }
    public string? GrowthHousingUnits2004 { get; set; }
    public string? GrowthIncreaseNumber { get; set; }
    public string? GrowthIncreasePercentage { get; set; }
    public string? Cbsapop2003 { get; set; }
    public string? CbsadivPop2003 { get; set; }
    public string? CongressionalDistrict { get; set; }
    public string? CongressionalLandArea { get; set; }
    public string? DeliveryResidential { get; set; }
    public string? DeliveryBusiness { get; set; }
    public string? DeliveryTotal { get; set; }
    public string? PreferredLastLineKey { get; set; }
    public string? ClassificationCode { get; set; }
    public string? MultiCounty { get; set; }
    public string? Csaname { get; set; }
    public string? CbsaDivName { get; set; }
    public string? CityStateKey { get; set; }
    public string? PopulationEstimate { get; set; }
    public string? LandArea { get; set; }
    public string? WaterArea { get; set; }
    public string? CityAliasCode { get; set; }
    public string? CityMixedCase { get; set; }
    public string? CityAliasMixedCase { get; set; }
    public string? BoxCount { get; set; }
    public string? Sfdu { get; set; }
    public string? Mfdu { get; set; }
}
