namespace Database.Trupanion.Entity.TruDat.Price;

public class TruDatPriceRateCardAgeFactor
{
    public string? AgeGroup { get; set; }
    public int? AnimalId { get; set; }
    public int? AgeId { get; set; }
    public double? StandardFactorCa { get; set; }
    public double? StandardFactorUs { get; set; }
    public double? Ab { get; set; }
    public double? Bc { get; set; }
    public double? Mb { get; set; }
    public double? Nb { get; set; }
    public double? Nl { get; set; }
    public double? Ns { get; set; }
    public double? Nt { get; set; }
    public double? Nu { get; set; }
    public double? On { get; set; }
    public double? Pe { get; set; }
    public double? Qc { get; set; }
    public double? Sk { get; set; }
    public double? Yt { get; set; }
    public double? Ak { get; set; }
    public double? Al { get; set; }
    public double? Ar { get; set; }
    public double? Az { get; set; }
    public double? Ca { get; set; }
    public double? Co { get; set; }
    public double? Ct { get; set; }
    public double? De { get; set; }
    public double? Dc { get; set; }
    public double? Fl { get; set; }
    public double? Ga { get; set; }
    public double? Hi { get; set; }
    public double? Id { get; set; }
    public double? Il { get; set; }
    public double? In { get; set; }
    public double? Ia { get; set; }
    public double? Ks { get; set; }
    public double? Ky { get; set; }
    public double? La { get; set; }
    public double? Me { get; set; }
    public double? Md { get; set; }
    public double? Ma { get; set; }
    public double? Mi { get; set; }
    public double? Mn { get; set; }
    public double? Ms { get; set; }
    public double? Mo { get; set; }
    public double? Mt { get; set; }
    public double? Ne { get; set; }
    public double? Nv { get; set; }
    public double? Nh { get; set; }
    public double? Nj { get; set; }
    public double? Nm { get; set; }
    public double? Ny { get; set; }
    public double? Nc { get; set; }
    public double? Nd { get; set; }
    public double? Oh { get; set; }
    public double? Ok { get; set; }
    public double? Or { get; set; }
    public double? Ri { get; set; }
    public double? Sc { get; set; }
    public double? Sd { get; set; }
    public double? Tn { get; set; }
    public double? Tx { get; set; }
    public double? Ut { get; set; }
    public double? Vt { get; set; }
    public double? Va { get; set; }
    public double? Wa { get; set; }
    public double? Wv { get; set; }
    public double? Wi { get; set; }
    public double? Wy { get; set; }
    public double? Pr { get; set; }
    public double? Pa { get; set; }
    public DateTime? Updated { get; set; }
    public string? RateCardName { get; set; }
}
